# Sniperkit-Bot
# - Status: analyzed

build:
  flags: '-tags netgo'
  ldflags: '-X main.version={{ .Version }}'
  env:
    - 'CGO_ENABLED=0'
  goos:
    - 'linux'
    - 'darwin'
  goarch:
    - 'amd64'
archive:
  format: 'tar.gz'
